### ISSUE TITLE
已经连接上了，提示Peripheral is not connected. Please make a connection first!!

### ISSUE THREAD

**Issue by jasonpakio** [enix223/SkyBlue#3]

**Comment by enix223** [comment]
是不是链接丢失？可否把后台日志粘贴上来？

**Comment by enix223** [comment]
我也发现这个问题了，是链接成功的回调在设备状态改变之前，所以出现设备状态的不一致。已经修复了，可以升级到 0.2.1

**Comment by jasonpakio** [comment]
OK,就是那里的状态没有改变所以执行不下去，我试试

**Comment by jasonpakio** [comment]
就是我现在遇到点问题，就是我现在在你的这个库里面获取不到蓝牙的状态、已经连接的外设，有时候我这边有点问题我需要将已经连接的外设断开。CBMANAGER那点的代理方法 DIDCONNECT 和DISCONNECT能否有一个代理写出来，我现在去获取这些就要修改你库里面的东西

**Comment by enix223** [comment]
`BLEManager`里面有一个成员`connectedPeripherals`是存放已经链接成功的设备的字典，你可以遍历它得到已经链接过的设备。

断开链接也有对应的方法：`-disconnectPeripheral:completion`。

你需要直接去调用`CBCentralManager`的`disconnect`是因为之前的那个问题么？所以才需要去修改这个库？

**Comment by jasonpakio** [comment]
DISCONNECT 这个方法不用修改库，  CBCentralManager 的代理需要修改，不然我就获取不到它的这个代理；      我连接成功的设备在BLEManager 的connectedPeripherals 里面没有，是空的，但是系统的蓝牙是已经连接上的

**Comment by enix223** [comment]
你的意思是，设备连接上了，但是`connectedPeripherals`是空的？如果是这样，那就是这个库还有问题，你可以贴一下输出的日志给我看看么？

**Comment by jasonpakio** [comment]
刚试了一下，连接过后那个connectedPeripherals里面又有了

**Comment by jasonpakio** [comment]
谢啦，我先发现看有其他什么问题没，再来找你    😝

**Comment by enix223** [comment]
好的，目前就我一个人在用，所以不知道别人会不会用起来不顺手
